CREATE TABLE IF NOT EXISTS `b_awz_weather_history` (
`ID` int(18) NOT NULL AUTO_INCREMENT,
`LAT_LON_MD5` varchar(32) NOT NULL,
`PROVIDER` varchar(32) NOT NULL,
`PARAMS` text DEFAULT NULL,
`DATE_DAY` datetime NOT NULL,
`DATE_UP` datetime NOT NULL,
PRIMARY KEY (`ID`),
unique IX_PROVIDER_DATE_DAY_LAT_LON_MD5 (PROVIDER, DATE_DAY, LAT_LON_MD5)
);