CREATE TABLE IF NOT EXISTS `b_awz_weather_history` (
ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
LAT_LON_MD5 varchar(32) NOT NULL,
PROVIDER varchar(32) NOT NULL,
PARAMS text,
DATE_DAY timestamp,
DATE_UP timestamp,
PRIMARY KEY (`ID`)
);
CREATE UNIQUE INDEX b_awz_weather_history_ix_provider_date_day_lat_lon_md5 ON b_awz_weather_history (provider, date_day, lat_lon_md5);